# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-59444d65-c438-426e-b02f-eeacdb1e7a66";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-59444d65-c438-426e-b02f-eeacdb1e7a66".device = "/dev/disk/by-uuid/59444d65-c438-426e-b02f-eeacdb1e7a66";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8151-2452";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2195aaa6-86fb-4bae-beb5-788bd215c347"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
